# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
import numpy as np
a=np.arange(10)
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
a=np.arange(10).reshape((2,5))
b=np.ones((2,5),dtype="int32")
c=np.vstack((a,b))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [15]:
c=np.hstack((a,b))
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [19]:
arr1= np.array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])
arr1 = arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [21]:
arr1.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [24]:

rm = np.random.randint(100, size=(5,5))
print("===:Input random array:===\n",rm)
print("===:Output Square of Array:=== \n")
print(rm ** 2)

===:Input random array:===
 [[62 92 87 73 59]
 [93 57 99 33 95]
 [88 27 56 33 16]
 [78 89 73 62 89]
 [93 73 55 75 69]]
===:Square of Array:=== 

[[3844 8464 7569 5329 3481]
 [8649 3249 9801 1089 9025]
 [7744  729 3136 1089  256]
 [6084 7921 5329 3844 7921]
 [8649 5329 3025 5625 4761]]


## Question:8

### Create 5x6 an array and find the mean?

In [25]:
rm1 = np.random.randint(100, size=(5,6))
print("===:Input random array:===\n",rm1)
print("===:Output mean of Array:=== \n")
print(rm1.mean())

===:Input random array:===
 [[66  0 49 41 14 95]
 [62 28 41 55  0 77]
 [22 73 46 93 54 39]
 [95 69 37 53  7 39]
 [ 0 49 45 92 94 94]]
===:Output mean of Array:=== 

50.96666666666667


## Question:9

### Find the standard deviation of the previous array in Q8?

In [26]:
print("===:Input random array:===\n",rm1)
print("===:Standard deviation of Array:=== \n")
print(np.std(rm1))

===:Input random array:===
 [[66  0 49 41 14 95]
 [62 28 41 55  0 77]
 [22 73 46 93 54 39]
 [95 69 37 53  7 39]
 [ 0 49 45 92 94 94]]
===:Standard deviation of Array:=== 

29.49856870350756


## Question:10

### Find the median of the previous array in Q8?

In [27]:
print("===:Input random array:===\n",rm1)
print("===:median of Array:=== \n")
print(np.median(rm1))

===:Input random array:===
 [[66  0 49 41 14 95]
 [62 28 41 55  0 77]
 [22 73 46 93 54 39]
 [95 69 37 53  7 39]
 [ 0 49 45 92 94 94]]
===:median of Array:=== 

49.0


## Question:11

### Find the transpose of the previous array in Q8?

In [28]:
print("===:Input random array:===\n",rm1)
print("===:transpose of Array:=== \n")
print(np.transpose(rm1))

===:Input random array:===
 [[66  0 49 41 14 95]
 [62 28 41 55  0 77]
 [22 73 46 93 54 39]
 [95 69 37 53  7 39]
 [ 0 49 45 92 94 94]]
===:transpose of Array:=== 

[[66 62 22 95  0]
 [ 0 28 73 69 49]
 [49 41 46 37 45]
 [41 55 93 53 92]
 [14  0 54  7 94]
 [95 77 39 39 94]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [31]:
rm2 = np.random.randint(20, size=(4,4))
print("===:Input random array:===\n",rm2)
print("===:sum of diagonal elements in Array:=== \n")
print(np.trace(rm2))

===:Input random array:===
 [[16 11 16 16]
 [ 2  6  9 19]
 [14 18  3 19]
 [ 0  5 17  1]]
===:sum of diagonal elements in Array:=== 

26


## Question:13

### Find the determinant of the previous array in Q12?

In [32]:
print("===:Input random array:===\n",rm2)
print("===:determinant of Array:=== \n")
print(np.linalg.det(rm2))


===:Input random array:===
 [[16 11 16 16]
 [ 2  6  9 19]
 [14 18  3 19]
 [ 0  5 17  1]]
===:determinant of Array:=== 

48444.00000000005


## Question:14

### Find the 5th and 95th percentile of an array?

In [38]:
print("===:Input random array:===\n",rm2)
print("\n")
print(" ===:5th percentile of array:===\n",np.percentile(rm2, 5))
print("===:95th percentile of array:===\n",np.percentile(rm2, 95))

===:Input random array:===
 [[16 11 16 16]
 [ 2  6  9 19]
 [14 18  3 19]
 [ 0  5 17  1]]


 ===:5th percentile of array:===
 0.75
===:95th percentile of array:===
 19.0


## Question:15

### How to find if a given array has any null values?

In [34]:
print("===:Input random array:===\n",rm2)
print("===:array has any null values:=== \n")
print(np.isnan(rm2).any())

===:Input random array:===
 [[16 11 16 16]
 [ 2  6  9 19]
 [14 18  3 19]
 [ 0  5 17  1]]
===:array has any null values:=== 

False
