# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [160]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [161]:
v = np.arange(10,50)
print("vector ranging from 10 to 49:")


print(v)

vector ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [7]:
print(v.shape)

(40,)


5. Print the type of the previous array in question 3

In [ ]:
print(v.dtype)

6. Print the numpy version and the configuration


In [8]:
print("NumPy Version:",np.__version__)
print("NumPy Config",np.show_config())

NumPy Version: 1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Saadat.Ali/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Saadat.Ali/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Saadat.Ali/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libra

7. Print the dimension of the array in question 3


In [10]:
print("Dimension : ",v.ndim)

Dimension :  1


8. Create a boolean array with all the True values

In [11]:
np.ones((5), dtype=bool)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [26]:
nd = np.ndarray((2,3))
print("Input Array : \n",nd)
print("Array Dimension: ",nd.ndim)

Input Array : 
 [[0. 0. 0.]
 [0. 0. 0.]]
Array Dimension:  2


10. Create a three dimensional array



In [33]:
nd3 = np.ndarray((3,3,4))
print("Input Array : \n",nd3)
print("Array Dimension: ",nd3.ndim)

Input Array : 
 [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Array Dimension:  3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [36]:
A = np.arange(8)
print("Method 1 using np.flip : ", np.flip(A))
print("Method 2 using array indexes : ", A[::-1])

Method 1 using np.flip :  [7 6 5 4 3 2 1 0]
Method 2 using array indexes :  [7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [37]:
x = np.zeros(10)
x[4]=1
print("vector of size 10 but the fifth value which is 1 : ",x)

vector of size 10 but the fifth value which is 1 :  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [38]:
array_2D=np.identity(3)
print('===: 3x3 identity matrix:===\n')
print(array_2D)

===: 3x3 identity matrix:===

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [41]:
arr = np.array([1, 2, 3, 4, 5])
print("Old dtype: ",arr.dtype)
arr = arr.astype(float)
print("New dtype :",arr.dtype)

Old dtype:  int32
New dtype : float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [44]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
print('===: Input arr1 :===\n',arr1)

print('===: Input arr2 :===\n',arr2)
mularr = np.multiply(arr1, arr2)
print('===: Multiply arr1 with arr2 :===\n')
print(mularr)
print('===: ====================== :===\n')

===: Input arr1 :===
 [[1. 2. 3.]
 [4. 5. 6.]]
===: Input arr2 :===
 [[ 0.  4.  1.]
 [ 7.  2. 12.]]
===: Multiply arr1 with arr2 :===

[[ 0.  8.  3.]
 [28. 10. 72.]]
===: ====================== :===



16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [46]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
print('===: Input arr1 :===\n',arr1)

print('===: Input arr2 :===\n',arr2)
cmp = arr1 == arr2
print('===: comparing both the arrays :===\n',cmp)
print("===: ====================== :===\n")

===: Input arr1 :===
 [[1. 2. 3.]
 [4. 5. 6.]]
===: Input arr2 :===
 [[ 0.  4.  1.]
 [ 7.  2. 12.]]
===: comparing both the arrays :===
 [[False False False]
 [False False False]]
===: ====================== :===



17. Extract all odd numbers from arr with values(0-9)

In [47]:
arr = np.arange(10)
filter_arr = (arr % 2 == 1)
newarr = arr[filter_arr]
print('all odd numbers from arr with values(0-9)')
print(newarr)

all odd numbers from arr with values(0-9)
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [48]:
arr = np.arange(10)
arr[arr % 2 ==1]= -1
print('Replace all odd numbers to -1')
print(arr)

Replace all odd numbers to -1
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [50]:
arr = np.arange(10)
print('Input array : \n',arr)
print('Replace the values of indexes 5,6,7 and 8 to 12')
arr[5:9] = 12
print(arr)
print("===: ====================== :===\n")

Input array : 
 [0 1 2 3 4 5 6 7 8 9]
Replace the values of indexes 5,6,7 and 8 to 12
[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [52]:
x = np.ones((3,3))
print("====:Input array:====\n")
print(x)
print("2d array with 1 on the border and 0 inside")
x[1:-1,1:-1]=0
print(x)
print("===: ====================== :===\n")

====:Input array:====

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2d array with 1 on the border and 0 inside
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [55]:
arr2d = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
print("====: Input Array :====\n",arr2d)
print('Replace the value 5 to 12')
arr2d[arr2d==5]=12
print(arr2d)
print("===: ====================== :===\n")

====: Input Array :====
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Replace the value 5 to 12
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]
===: ====================== :===



22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [58]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print("====: Input Array :====\n",arr3d)
print("====: Output Array :====\n")
print("Convert all the values of 1st array to 64")
arr3d[0]=64
print(arr3d)

====: Input Array :====
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
====: Output Array :====

Convert all the values of 1st array to 64
[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [64]:
arr = np.arange(10).reshape(2, 5)
print('2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it')
print("====: Input Array :====\n",arr)
print("====: Output Array :====\n",arr[0])


2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
====: Input Array :====
 [[0 1 2 3 4]
 [5 6 7 8 9]]
====: Output Array :====
 0


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [65]:
arr = np.arange(10).reshape(2, 5)
print("====: Input Array :====\n",arr)
print('2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it')
print("====: Output Array :====\n",arr[1][1])
print("===: ====================== :===\n")

====: Input Array :====
 [[0 1 2 3 4]
 [5 6 7 8 9]]
2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
====: Output Array :====
 6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [67]:
arr = np.arange(10).reshape(2,5)
print('2-Dimensional array with values 0-9 and slice out the third column but only the first two rows')
print("====: Input Array :====\n",arr)
print("====: Output Array :====\n",arr[0:2,2:3])
print("===: ====================== :===\n")

2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
====: Input Array :====
 [[0 1 2 3 4]
 [5 6 7 8 9]]
====: Output Array :====
 [[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [68]:
##(6) Create a 10x10 array with random values and find the minimum and maximum values
values = np.random.randn(10,10)
print("====: Input Array :====\n",values)

print("====: Output min in Array Method 1 using array.min() :====\n",values.min())
print("====: Output min in Array Method 2 using np.min :====\n",np.min(values))
print("====: Output min in Array Method 3 using np.amin(array):====\n",np.amin(values))
print("====: Output min in Array Method 4 using min(array.flatten()):====\n",min(values.flatten()))

print("====: Output min in Array Method 1 using array.max() :====\n",values.max())
print("====: Output min in Array Method 2 using np.max(array) :====\n",np.max(values))
print("====: Output min in Array Method 3 using np.amax(array):====\n",np.amax(values))
print("====: Output min in Array Method 4 using max(array.flatten()):====\n",max(values.flatten()))

====: Input Array :====
 [[ 0.98504751 -0.00746552 -0.26567237 -0.1517291  -1.21773336  1.24244462
  -0.94797138 -1.43072692  0.43763485 -0.73253878]
 [ 1.53966146 -0.52101245 -0.06030376  0.02578793  0.17492882 -0.88942674
   0.64353067  0.24674173  0.93089769 -0.01103851]
 [ 0.47927744  0.15932358  0.82160895 -0.45046071 -0.88027174 -0.99575098
  -0.52000604  0.27123135  0.57256864  1.953768  ]
 [ 0.09758626 -1.369914    0.51054485  0.7945538  -0.39287164  0.29731628
   1.30928878  2.0846642   2.36363981 -1.26051348]
 [ 0.25965921 -0.16542041 -0.07355176  1.15142916 -0.98031422  1.42787413
  -1.04385992 -1.04651656  1.88256877 -0.05674283]
 [-1.44850879 -0.05764063  0.14752952 -0.33925371 -2.37904924  0.19163163
  -0.1776983  -0.73065401  0.89997088  2.04391874]
 [ 0.52389401  0.26538886  0.74336186 -1.03852184 -0.51458058  0.65579473
  -0.2983972  -1.4366642   0.30467352  0.65855431]
 [-2.18776993 -0.34906241 -0.15519734  1.20324871  1.30826752  1.19595909
   0.32812856  0.07836866 

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [71]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("====: Input Array a:====\n",a)
print("====: Input Array b:====\n",b)
# Common values between two arrays 
print("Common values between two arrays \n",np.intersect1d(a, b))

====: Input Array a:====
 [1 2 3 2 3 4 3 4 5 6]
====: Input Array b:====
 [ 7  2 10  2  7  4  9  4  9  8]
Common values between two arrays 
 [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [152]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("====: Input Array a:====\n",a)
print("====: Input Array b:====\n",b)
boolArr = np.where(a==b)
print((a==b))
print(np.where(a==b))
print("Indexes where element matched is : ",boolArr[0])
print("===: ====================== :===\n")

====: Input Array a:====
 [1 2 3 2 3 4 3 4 5 6]
====: Input Array b:====
 [ 7  2 10  2  7  4  9  4  9  8]
[False  True False  True False  True False  True False False]
(array([1, 3, 5, 7], dtype=int64),)
Indexes where element matched is :  [1 3 5 7]
===: ====================== :===



29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [79]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print("====: Input Array names:====\n",names)
print("====:  Output Array names are not equal to 'Will' :====")
narr = (names !='Will')
print(names[narr])
print("===: ====================== :===\n")

====: Input Array names:====
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
====:  Output Array names are not equal to 'Will' :====
['Bob' 'Joe' 'Bob' 'Joe' 'Joe']
===: ====================== :===



30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [83]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print("====: Input Array names:====\n",names)

print("====:  Output names are not equal to Will and Joe :====")
print("=>Without np.where Clause")
narr = (names !='Will') & (names !='Joe' )

print(names[narr])
print("=>With np.where")
narr1 = np.where((names !='Will')&(names !='Joe'))
print(names[narr1])
print("===: ====================== :===\n")

====: Input Array names:====
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
====:  Output names are not equal to Will and Joe :====
=>Without np.where Clause
['Bob' 'Bob']
=>With np.where
['Bob' 'Bob']
===: ====================== :===



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [86]:
arr = np.arange(1,16)
print("====: Input Array :====\n",arr)

arr = arr.reshape(5, 3)

print("====:  Output Reshape(5x3) :====")
print(arr)

====: Input Array :====
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
====:  Output Reshape(5x3) :====
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [87]:
arr = np.arange(1,17)
print("====: Input Array :====\n",arr)
arr = arr.reshape(2, 2, 4)
print("====:  Output Reshape (2, 2, 4)  :====")
print(arr)

====: Input Array :====
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
====:  Output Reshape (2, 2, 4)  :====
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [90]:
arr = np.arange(1,17).reshape(2, 2, 4)
print("====: Input Array :====\n",arr)
print("====:  Output Swap axes  :====")
print(np.swapaxes(arr,1,2))

====: Input Array :====
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
====:  Output Swap axes  :====
[[[ 1  5]
  [ 2  6]
  [ 3  7]
  [ 4  8]]

 [[ 9 13]
  [10 14]
  [11 15]
  [12 16]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [102]:
arr = np.arange(10)

print(f"====: Input Array (size: {arr.size}):====\n",arr)
sqrt_arr=np.sqrt(arr)
print("====:  Output :====")
print("====:  square root of every element  :====\n",sqrt_arr)
sqrt_arr[sqrt_arr<(0.5)]=0
print("====:  values less than 0.5, replace them with 0  :====\n",sqrt_arr)


====: Input Array (size: 10):====
 [0 1 2 3 4 5 6 7 8 9]
====:  Output :====
====:  square root of every element  :====
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
====:  values less than 0.5, replace them with 0  :====
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [119]:
a = np.random.randint(50, size=(12))
b = np.random.randint(50, size=(12))
print(f"====: Input Array a (size: {a.size}):====\n",a)
print(f"====: Input Array b (size: {b.size}):====\n",b)
print("====:  Output :====")
#print("Max Value in List using array.max() (A) : ", a.max())
#print("Max Value in List using array.max() (B) : ", b.max())
print("Max Value in List using np.max (A) : ",np.max(a))
print("Max Value in List using np.max(B) : ",np.max(b))
newarr = np.array((np.max(a),np.max(b)))
print("===: New Array of (Max A and Max B) :=== ",newarr)

====: Input Array a (size: 12):====
 [19 41  6 25  4 14 19  9 16 34  0 27]
====: Input Array b (size: 12):====
 [ 4 32 27  4 37 31 43 35 39  5 49 27]
====:  Output :====
Max Value in List using np.max (A) :  41
Max Value in List using np.max(B) :  49
===: New Array of (Max A and Max B) :===  [41 49]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [123]:
names = np.array(['Bob', 'Joe', 'Will','Bob', 'Will', 'Joe', 'Joe'])
print("====:Input Array:==== \n ",names)

print("====:  Output :====")
# np.lookfor('unique')
unique_arr = np.unique(names)
print("===:After Unique without Sort:==== \n ",unique_arr)
# np.lookfor('sort')
unique_sort_arr = np.sort(unique_arr)
print("====:After Sorting :==== \n ",unique_sort_arr)
print("\n ===================================== \n")

====:Input Array:==== 
  ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
====:  Output :====
===:After Unique without Sort:==== 
  ['Bob' 'Joe' 'Will']
====:After Sorting :==== 
  ['Bob' 'Joe' 'Will']




37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [124]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print("===:Input array a:===",a)
print("===:Input array b:===",b)
print("====:  Output :====")
Not_in_b = np.in1d(a, b,invert=True)
print("a not in b",a[Not_in_b])
print("\n ===================================== \n")


===:Input array a:=== [1 2 3 4 5]
===:Input array b:=== [5 6 7 8 9]
====:  Output :====
a not in b [1 2 3 4]




38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [133]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

print("===:Input array sampleArray:===\n",sampleArray)
print("===:Input array newColumn:===\n",newColumn)
print("===================================== \n")
print("========:  Output using reshape & Slicing:========")
newColumn =newColumn.reshape(3,1)
print("reshape newColumn to column wise array \n",newColumn)

print("Method 1: Replace newColumn usingreshape & Slicing [::,1:2:] \n")
print("===:Before Replace:=== \n",sampleArray)
print("===:Sliced Values:=== \n",sampleArray[::,1:2:])
sampleArray[::,1:2:]=newColumn.reshape(3,1)

print("===:After Replaced Sliced Values:=== \n",sampleArray)

print("\n ===================================== \n")

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
#newColumn =newColumn.reshape(3,1)

print("Method 2: using np.delete & np.insert \n")
sampleArray = np.delete(sampleArray, 1, 1)

print("===:After Delete column two:=== \n",sampleArray)

sampleArray = np.insert(sampleArray, 1, newColumn, axis=1)
print("===:After Insert newColumn:=== \n",sampleArray)

print("\n ===================================== \n")

===:Input array sampleArray:===
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
===:Input array newColumn:===
 [[10 10 10]]

========:  Output using reshape & Slicing:========
reshape newColumn to column wise array 
 [[10]
 [10]
 [10]]
Method 1: Replace newColumn usingreshape & Slicing [::,1:2:] 

===:Before Replace:=== 
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
===:Sliced Values:=== 
 [[43]
 [22]
 [94]]
===:After Replaced Sliced Values:=== 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


Method 2: using np.delete & np.insert 

===:After Delete column two:=== 
 [[34 73]
 [82 12]
 [53 66]]
===:After Insert newColumn:=== 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]




39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [134]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

print("===:Input array x:===\n",x)
print("===:Input array y:===\n",y)
print("========:  Output dot(x,y) product using np.dot:========")
print("\n",np.dot(x, y))

print("\n ===================================== \n")

===:Input array x:===
 [[1. 2. 3.]
 [4. 5. 6.]]
===:Input array y:===
 [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

 [[ 28.  64.]
 [ 67. 181.]]




40. Generate a matrix of 20 random values and find its cumulative sum

In [139]:
rm = np.random.randint(100, size=(20)).reshape(5,4)


print(f"===:Random Matrix (size: {a.size}):=== \n",rm)
print("===:Output Cumulative sum of Random Matrix:=== \n",np.cumsum(rm))
print("===================================== \n")

===:Random Matrix (size: 5):=== 
 [[42 71 37 75]
 [98 26  0 29]
 [50 72 13 11]
 [31 85 82 34]
 [64 67 41 29]]
===:Output Cumulative sum of Random Matrix:=== 
 [ 42 113 150 225 323 349 349 378 428 500 513 524 555 640 722 756 820 887
 928 957]

